### ISSUE TITLE
Minima implementazione del Manager

### ISSUE THREAD

**Issue by Friedchicken-42** [Friedchicken-42/progettoIngegneriaSoftware#6]
Ci serve almeno una basica implementazione per fare un bridge tra i vari componenti (`Database`, `Api`, ...) e la grafica

**Comment by Friedchicken-42** [comment]
Possibile implementazione a callback:
```kotlin
binding.button.setOnClickListener {
    binding.progressBar.visibility = View.VISIBLE

    Manager.something(lifecycle) { data ->
        println("after something")
        binding.textView.text = data
        binding.progressBar.visibility = View.GONE
    }
}
```

In questo caso `something` non e' bloccante e viene killata se cambiamo `Fragment`

Volendo si puo' aggiungere un'altra lambda opzionale per gestire gli errori
```kotlin
Manager.something(lifecycle, done = { .. }, error = { .. })
```

**Comment by LucaBarban** [comment]
Così dovrebbe andare bene, il contesto lo si riesce comunque a passare

**Comment by Friedchicken-42** [comment]
Ok la versione completa dovrebbe essere
```kotlin
run(
    lifecycle,
    Manager::something,
    done = { .. },
    error = { .. },
    cleanup = { .. },
)
```
con `error` e `cleanup` opzionali
